[package]
name = "silver-octo-train"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
termion = "2.0.3"
